#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "fir_coeffs.h"   // generated by MATLAB
#include "input_data.h"   // generated by MATLAB

int main(void)
{
    int N = FIR_LEN;          // number of b coefficients
    int L = INPUT_LEN;        // input length
    float *y = (float*)malloc(sizeof(float)*L);
    float *delay = (float*)calloc(N, sizeof(float)); // N taps ring buffer
    for (int n=0; n<L; ++n) {
        // shift delay line (simple method)
        for (int k=N-1; k>0; --k) delay[k] = delay[k-1];
        delay[0] = input_data[n];
        // convolution dot-product
        float acc = 0.0f;
        for (int k=0; k<N; ++k) acc += fir_b[k] * delay[k];
        y[n] = acc;
    }
    // write output to file
    FILE *fout = fopen("output_fir.txt", "w");
    if (!fout) {
        printf("Failed to open output_fir.txt for writing\n");
        return -1;
    }
    for (int n=0; n<L; ++n) fprintf(fout, "%1.9f\n", y[n]);
    fclose(fout);
    // also print a short summary to console
    printf("FIR processing done. Wrote %d samples to output_fir.txt\n", L);
    free(y);
    free(delay);
    return 0;
}
