#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "iir_coeffs.h"    // generated by MATLAB
#include "input_data.h"    // generated by MATLAB
int main(void)
{
    int Bn = IIR_B_LEN;   // number of b coefficients (M+1)
    int An = IIR_A_LEN;   // number of a coefficients (N+1) (a0..aN)
    int L = INPUT_LEN;
    float *y = (float*)malloc(sizeof(float)*L);
    float *xbuf = (float*)calloc(Bn, sizeof(float));
    float *ybuf = (float*)calloc(An, sizeof(float));
    for (int n=0; n<L; ++n) {
        // push new input into xbuf (shift right)
        for (int i=Bn-1; i>0; --i) xbuf[i] = xbuf[i-1];
        xbuf[0] = input_data[n];
        // compute numerator sum b * x[]
        float num = 0.0f;
        for (int i=0; i<Bn; ++i) num += iir_b[i] * xbuf[i];
        // compute denominator sum a[1..N]*y[1..N]
        float den = 0.0f;
        for (int j=1; j<An; ++j) den += iir_a[j] * ybuf[j-1]; // ybuf stores previous outputs y[n-1]..y[n-N]
        // y[n] = (num - den) / a0
        float out = (num - den) / iir_a[0];
        // shift ybuf
        for (int j=An-2; j>0; --j) ybuf[j] = ybuf[j-1];
        if (An-1 > 0) ybuf[0] = out;

        y[n] = out;
    }
    FILE *fout = fopen("output_iir.txt", "w");
    if (!fout) {
        printf("Failed to open output_iir.txt\n");
        return -1;
    }
    for (int n=0; n<L; ++n) fprintf(fout, "%1.9f\n", y[n]);
    fclose(fout);
    printf("IIR processing done. Wrote %d samples to output_iir.txt\n", L);
    free(y);
    free(xbuf);
    free(ybuf);
    return 0;
}
